name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: gcc
            config: cmake
          - compiler: clang
            config: cmake
          - compiler: clang
            config: asan
          - compiler: clang
            config: tsan
          - compiler: clang
            config: format
          - compiler: clang
            config: scan-build

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure Build & Test
      shell: bash
      env:
        CC: ${{ matrix.compiler }}
      run: ./travis.sh ${{ matrix.config }}

  build-macox:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Configure Build & Test
      shell: bash
      run: ./travis.sh macos

  build-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/cache@v2
      with:
        path: c:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: chocolatey-cache-${{ hashFiles('.github/workflows/ci.yml') }}
    - name: Install Prerequisites
      run: choco install openssl
    - name: Configure Build & Test
      shell: bash
      run: |
        cmake -E make_directory build/
        cmake -S . -B build/
        cmake --build build/ --config Debug --target INSTALL
        ctest -V build/
